### ISSUE TITLE
单独安装think-cache插件后在php8.1版本中运行错误

### ISSUE THREAD

**Issue by AiMuC** [top-think/think-cache#13]
依赖 topthink/think-container 这个没有兼容php8.0  topthink/think-container内已提交兼容php8
在使用php8.1运行时使用thinkcache 报 
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of think\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/wwwroot/*/vendor/topthink/think-container/src/Container.php:567
Stack trace:
#0 /www/wwwroot/*/vendor/topthink/think-container/src/Container.php(32): {closure}()

**Comment by bbuugg** [comment]
感觉没人维护了这个包

**Comment by banlancegit** [comment]
我去下载了tp包看了下,不兼容php8.1主要是这个扩展用了一个不支持8.1的库,然后对比tp6的区别,找到修改办法,
找到Driver文件里的 serialize 跟 unserialize 方法,分别改成下面代码.
1
       if (is_numeric($data)) {
            return (string) $data;
        }

        $serialize = $this->options['serialize'][0] ?? "serialize";

        return $serialize($data);




 2      
         if (is_numeric($data)) {
            return $data;
        }

        $unserialize = $this->options['serialize'][1] ?? "unserialize";

        return $unserialize($data);

**Comment by liu21st** [comment]
如果使用的是TP 不需要这个库 如果不是使用TP 有很多的缓存库可以使用 所以不建议使用这个
